package study.entity;
// Generated 26 Mar, 2022 8:59:56 AM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ComplaintTable generated by hbm2java
 */

@Entity
@Table(name = "complaint_table", catalog = "water_jar_management")
public class ComplaintTable implements java.io.Serializable {

	private Integer complaintId;
	private Customer customerInfoTable;
	private String complaintInfo;
	private Date complaintDate;
	private String complaintStatus;
	private Set complaintCommentTables = new HashSet(0);

	public ComplaintTable() {
	}

	public ComplaintTable(Customer customerInfoTable) {
		this.customerInfoTable = customerInfoTable;
	}

	public ComplaintTable(Customer customerInfoTable, String complaintInfo, Date complaintDate,
			String complaintStatus, Set complaintCommentTables) {
		this.customerInfoTable = customerInfoTable;
		this.complaintInfo = complaintInfo;
		this.complaintDate = complaintDate;
		this.complaintStatus = complaintStatus;
		this.complaintCommentTables = complaintCommentTables;
	}
	
	
	

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "complaint_id", unique = true, nullable = false)
	public Integer getComplaintId() {
		return this.complaintId;
	}

	public void setComplaintId(Integer complaintId) {
		this.complaintId = complaintId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_id", nullable = false)
	public Customer getCustomerInfoTable() {
		return this.customerInfoTable;
	}

	public void setCustomerInfoTable(Customer customerInfoTable) {
		this.customerInfoTable = customerInfoTable;
	}

	@Column(name = "complaint_info", length = 300)
	public String getComplaintInfo() {
		return this.complaintInfo;
	}

	public void setComplaintInfo(String complaintInfo) {
		this.complaintInfo = complaintInfo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "complaint_date", length = 19)
	public Date getComplaintDate() {
		return this.complaintDate;
	}

	public void setComplaintDate(Date complaintDate) {
		this.complaintDate = complaintDate;
	}

	@Column(name = "complaint_status", length = 100)
	public String getComplaintStatus() {
		return this.complaintStatus;
	}

	public void setComplaintStatus(String complaintStatus) {
		this.complaintStatus = complaintStatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "complaintTable")
	public Set<ComplaintComment> getComplaintCommentTables() {
		return this.complaintCommentTables;
	}

	public void setComplaintCommentTables(Set complaintCommentTables) {
		this.complaintCommentTables = complaintCommentTables;
	}

	@Override
	public String toString() {
		return "ComplaintTable [complaintId=" + complaintId + ", customerInfoTable=" + customerInfoTable
				+ ", complaintInfo=" + complaintInfo + ", complaintDate=" + complaintDate + ", complaintStatus="
				+ complaintStatus + ", complaintCommentTables=" + complaintCommentTables + "]";
	}
	
	

}
