package study.entity;
// Generated 26 Mar, 2022 8:59:56 AM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CustomerBillTable generated by hbm2java
 */
@Entity
@Table(name = "customer_bill_table", catalog = "water_jar_management")
public class CustomerBill implements java.io.Serializable {

	private Integer customerBillId;
	private Customer customer;
	private Date customerBillDateTime;
	private String customerBillForMonth;
	private Integer totalOrderDays;
	private Integer totalQuantity;
	private Integer totalAmountRs;
	private String customerBillStatus;

	public CustomerBill() {
	}

	public CustomerBill(Customer customer) {
		this.customer = customer;
	}

	public CustomerBill(Customer customer, Date customerBillDateTime,
			String customerBillForMonth, Integer totalOrderDays, Integer totalQuantity, Integer totalAmountRs,
			String customerBillStatus) {
		this.customer = customer;
		this.customerBillDateTime = customerBillDateTime;
		this.customerBillForMonth = customerBillForMonth;
		this.totalOrderDays = totalOrderDays;
		this.totalQuantity = totalQuantity;
		this.totalAmountRs = totalAmountRs;
		this.customerBillStatus = customerBillStatus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "customer_bill_id", unique = true, nullable = false)
	public Integer getCustomerBillId() {
		return this.customerBillId;
	}

	public void setCustomerBillId(Integer customerBillId) {
		this.customerBillId = customerBillId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_id", nullable = false)
	public Customer getCustomerInfoTable() {
		return this.customer;
	}

	public void setCustomerInfoTable(Customer customer) {
		this.customer = customer;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "customer_bill_date_time", length = 19)
	public Date getCustomerBillDateTime() {
		return this.customerBillDateTime;
	}

	public void setCustomerBillDateTime(Date customerBillDateTime) {
		this.customerBillDateTime = customerBillDateTime;
	}

	@Column(name = "customer_bill_for_month", length = 100)
	public String getCustomerBillForMonth() {
		return this.customerBillForMonth;
	}

	public void setCustomerBillForMonth(String customerBillForMonth) {
		this.customerBillForMonth = customerBillForMonth;
	}

	@Column(name = "total_order_days")
	public Integer getTotalOrderDays() {
		return this.totalOrderDays;
	}

	public void setTotalOrderDays(Integer totalOrderDays) {
		this.totalOrderDays = totalOrderDays;
	}

	@Column(name = "total_quantity")
	public Integer getTotalQuantity() {
		return this.totalQuantity;
	}

	public void setTotalQuantity(Integer totalQuantity) {
		this.totalQuantity = totalQuantity;
	}

	@Column(name = "total_amount_rs")
	public Integer getTotalAmountRs() {
		return this.totalAmountRs;
	}

	public void setTotalAmountRs(Integer totalAmountRs) {
		this.totalAmountRs = totalAmountRs;
	}

	@Column(name = "customer_bill_status", length = 100)
	public String getCustomerBillStatus() {
		return this.customerBillStatus;
	}

	public void setCustomerBillStatus(String customerBillStatus) {
		this.customerBillStatus = customerBillStatus;
	}

	@Override
	public String toString() {
		return "CustomerBill [customerBillId=" + customerBillId + ", customer=" + customer + ", customerBillDateTime="
				+ customerBillDateTime + ", customerBillForMonth=" + customerBillForMonth + ", totalOrderDays="
				+ totalOrderDays + ", totalQuantity=" + totalQuantity + ", totalAmountRs=" + totalAmountRs
				+ ", customerBillStatus=" + customerBillStatus + "]";
	}
	
	

}
