package study.entity;
// Generated 26 Mar, 2022 8:59:56 AM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * JarCategoryTable generated by hbm2java
 */
@Entity
@Table(name = "jar_category_table", catalog = "water_jar_management")
public class JarCategory implements java.io.Serializable {

	private Integer categoryId;
	private String jarCapacity;
	private String waterType;
	private Integer price;
	private Set subscriptionTables = new HashSet(0);
	private Set extraOrderTables = new HashSet(0);

	public JarCategory() {
	}

	public JarCategory(String jarCapacity, String waterType, Integer price) {
		this.jarCapacity = jarCapacity;
		this.waterType = waterType;
		this.price = price;
	}
	

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "category_id", unique = true, nullable = false)
	public Integer getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "jar_capacity", length = 100)
	public String getJarCapacity() {
		return this.jarCapacity;
	}

	public void setJarCapacity(String jarCapacity) {
		this.jarCapacity = jarCapacity;
	}

	@Column(name = "water_type", length = 100)
	public String getWaterType() {
		return this.waterType;
	}

	public void setWaterType(String waterType) {
		this.waterType = waterType;
	}

	@Column(name = "price")
	public Integer getPrice() {
		return this.price;
	}

	public void setPrice(Integer price) {
		this.price = price;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jarCategoryTable")
	public Set<Subscription> getSubscriptionTables() {
		return this.subscriptionTables;
	}

	public void setSubscriptionTables(Set subscriptionTables) {
		this.subscriptionTables = subscriptionTables;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jarCategoryTable")
	public Set<ExtraOrder> getExtraOrderTables() {
		return this.extraOrderTables;
	}

	public void setExtraOrderTables(Set extraOrderTables) {
		this.extraOrderTables = extraOrderTables;
	}

	@Override
	public String toString() {
		return "JarCategory [categoryId=" + categoryId + ", jarCapacity=" + jarCapacity + ", waterType=" + waterType
				+ ", price=" + price + ", subscriptionTables=" + subscriptionTables + ", extraOrderTables="
				+ extraOrderTables + "]";
	}
	
	

}
