package study.entity;
// Generated 26 Mar, 2022 8:59:56 AM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NonDeliveryRecord generated by hbm2java
 */
@Entity
@Table(name = "non_delivery_record", catalog = "water_jar_management")
public class NonDelivery implements java.io.Serializable {

	private Integer nonDeliveryRecordId;
	private Subscription subscription;
	private Date nonDeliveryDate;
	private String nonDeliveryStatus;

	public NonDelivery() {
	}

	public NonDelivery(Subscription subscription) {
		this.subscription = subscription;
	}

	public NonDelivery(Subscription subscription, Date nonDeliveryDate, String nonDeliveryStatus) {
		this.subscription = subscription;
		this.nonDeliveryDate = nonDeliveryDate;
		this.nonDeliveryStatus = nonDeliveryStatus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "non_delivery_record_id", unique = true, nullable = false)
	public Integer getNonDeliveryRecordId() {
		return this.nonDeliveryRecordId;
	}

	public void setNonDeliveryRecordId(Integer nonDeliveryRecordId) {
		this.nonDeliveryRecordId = nonDeliveryRecordId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "subscription_id", nullable = false)
	public Subscription getSubscriptionTable() {
		return this.subscription;
	}

	public void setSubscriptionTable(Subscription subscription) {
		this.subscription = subscription;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "non_delivery_date", length = 10)
	public Date getNonDeliveryDate() {
		return this.nonDeliveryDate;
	}

	public void setNonDeliveryDate(Date nonDeliveryDate) {
		this.nonDeliveryDate = nonDeliveryDate;
	}

	@Column(name = "non_delivery_status", length = 100)
	public String getNonDeliveryStatus() {
		return this.nonDeliveryStatus;
	}

	public void setNonDeliveryStatus(String nonDeliveryStatus) {
		this.nonDeliveryStatus = nonDeliveryStatus;
	}

	@Override
	public String toString() {
		return "NonDelivery [nonDeliveryRecordId=" + nonDeliveryRecordId + ", subscription=" + subscription
				+ ", nonDeliveryDate=" + nonDeliveryDate + ", nonDeliveryStatus=" + nonDeliveryStatus + "]";
	}
	
	

}
