package study.entity;
// Generated 26 Mar, 2022 8:59:56 AM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SubscriptionTable generated by hbm2java
 */
@Entity
@Table(name = "subscription_table", catalog = "water_jar_management")
public class Subscription implements java.io.Serializable {

	
	private Integer subscriptionId;
	private Customer customer;
	private JarCategory jarCategory;
	private Supplier supplier;
	private Date subscriptionStartDate;
	private Date subscriptionEndDate;
	private String subscriptionStatus;
	private Set nonDeliveryRecords = new HashSet(0);

	public Subscription() {
	}

	public Subscription(Customer customer, JarCategory jarCategory,
			Supplier supplier) {
		this.customer = customer;
		this.jarCategory = jarCategory;
		this.supplier = supplier;
	}
	
	public Subscription( int id ,String start_date , String end_Date)
	{
		this.subscriptionId = id;
		this.subscriptionStartDate = new Date(start_date);
		this.subscriptionEndDate = new Date(end_Date);
	}

	public Subscription(Customer customer, JarCategory jarCategory,
			Supplier supplier, Date subscriptionStartDate, Date subscriptionEndDate,
			String subscriptionStatus) {
		this.customer = customer;
		this.jarCategory = jarCategory;
		this.supplier = supplier;
		this.subscriptionStartDate = subscriptionStartDate;
		this.subscriptionEndDate = subscriptionEndDate;
		this.subscriptionStatus = subscriptionStatus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "subscription_id", unique = true, nullable = false)
	public Integer getSubscriptionId() {
		return this.subscriptionId;
	}

	public void setSubscriptionId(Integer subscriptionId) {
		this.subscriptionId = subscriptionId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_id", nullable = false)
	public Customer getCustomerInfoTable() {
		return this.customer;
	}

	public void setCustomerInfoTable(Customer customer) {
		this.customer = customer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "category_id", nullable = false)
	public JarCategory getJarCategoryTable() {
		return this.jarCategory;
	}

	public void setJarCategoryTable(JarCategory jarCategory) {
		this.jarCategory = jarCategory;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "supplier_id", nullable = false)
	public Supplier getSupplierInfoTable() {
		return this.supplier;
	}

	public void setSupplierInfoTable(Supplier supplier) {
		this.supplier = supplier;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "subscription_start_date", length = 10)
	public Date getSubscriptionStartDate() {
		return this.subscriptionStartDate;
	}

	public void setSubscriptionStartDate(Date subscriptionStartDate) {
		this.subscriptionStartDate = subscriptionStartDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "subscription_end_date", length = 10)
	public Date getSubscriptionEndDate() {
		return this.subscriptionEndDate;
	}

	public void setSubscriptionEndDate(Date subscriptionEndDate) {
		this.subscriptionEndDate = subscriptionEndDate;
	}

	@Column(name = "subscription_status", length = 100)
	public String getSubscriptionStatus() {
		return this.subscriptionStatus;
	}

	public void setSubscriptionStatus(String subscriptionStatus) {
		this.subscriptionStatus = subscriptionStatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "subscriptionTable")
	public Set<NonDelivery> getNonDeliveryRecords() {
		return this.nonDeliveryRecords;
	}

	public void setNonDeliveryRecords(Set nonDeliveryRecords) {
		this.nonDeliveryRecords = nonDeliveryRecords;
	}

	@Override
	public String toString() {
		return "Subscription [subscriptionId=" + subscriptionId + ", customer=" + customer + ", jarCategory="
				+ jarCategory + ", supplier=" + supplier + ", subscriptionStartDate=" + subscriptionStartDate
				+ ", subscriptionEndDate=" + subscriptionEndDate + ", subscriptionStatus=" + subscriptionStatus
				+ ", nonDeliveryRecords=" + nonDeliveryRecords + "]";
	}
	
	

}
